language: python
python:
- '2.7'
node_js:
- '0.10'
addons:
  sauce_connect: true
env:
  global:
  - secure: AD4TuJWM+avyR22gz/O22XrMDsZeW9IC0usdlEPtUOx7rgqwLLdsZvAaSW3lg4b+CeFltT/q6wnjSvmxq8icxqsRuBUc7JyTEntLzlEt6qo8Ayu61pycnRYelk7GXIilb85hT0MKrHh/QqD/7I/LtfrUmsnLDfUB0jYB6kdB2iM=
  - secure: BkxendxmhcAzpQcgJadvtiHrHQ1b7ZC43RKV1rDtHVrKvhjE4hzxPv3W+fnHYaZKcKNgtHPiRCMrRt9NUI+sy/25KF8hfN4vFpfhy8Hj0bZnDa0T8Usr4tBLy7JhI93ViUu4y/rSJLAWEuip6BSVaoC8+MyaOzbX9snv+Kox/IY=
services:
- memcached
before_install:
- gem update --system
- gem install sass compass
- npm install -g grunt-cli
- npm install grunt grunt-contrib-compass
- sudo apt-get install -qq memcached python-memcache
install:
- export DISPLAY=:99.0
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
- pip install --upgrade setuptools --use-mirrors
- pip install --use-mirrors --use-wheel --find-links=https://stream.onepercentclub.com/wheelhouse/
  -r requirements/ci_requirements.txt
- pip install Pillow --use-mirrors
- touch onepercentclub/settings/secrets.py
before_script:
- pip show bluebottle
- grunt compass:dist --bb_path="`pip show bluebottle | grep Location | cut -b11-`/bluebottle/common/static/sass"
script:
- python ./manage.py test --settings=onepercentclub.settings.travis --failfast -v
  1
notifications:
  hipchat:
    rooms:
      secure: lfQxEnp7TBqzVc61Wm8NhQiqkKg6YBSx9Ro1q3VTeUWsKzFS2p7OV1eKu8bXjCA9FaCaaxc/TxFaZcvUr2hzXJiW/VoZH4J/+yYp2yblhj5uzQuQl3oWRgY8eFK33rjelqnkolFSmrMkVWY6cw/M8DNrxoSqzQLP2Dn5jYxS6Jg=
