language: python
python:
- '2.7'
node_js:
- '0.10'
addons:
  sauce_connect: true
env:
  global:
  - secure: aJOXcRy7b35heVBlqSZRCiw9pNt34At87TgsKaCwEgf5/fC1CPFa8el9AtlyU6uw/dk1bCcfaqB9K5s9j//qm5ZQQE8Xgr57BJ7anqrW8VH2hE1gUb8AE+hv4zVWTUwK1wIg9njfXObqSiioSy20FihWPrut5OnE941TOK2Ffes=
  - secure: LHK8n6J/SAsMYMFHpAs7bVknu/zZ1ABK4CC5OuR/3bOOzFYPWzAgtclX6UEKL5BanxYYNH7qHVDCc6HB3RDknFk4+KtxidkysQmV8CwQiGlclBW+Uozo78a2VXPhvuB83IERwYohz49QlBiYzyXpOi5gwfx9nFBB6ExdffFFlXM=
services:
- memcached
before_install:
- gem update --system
- gem install sass compass
- npm install -g grunt-cli
- npm install grunt grunt-contrib-compass
- sudo apt-get install -qq memcached python-memcache
install:
- export DISPLAY=:99.0
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
- pip install --upgrade setuptools --use-mirrors
- pip install --use-mirrors --use-wheel --find-links=https://stream.onepercentclub.com/wheelhouse/
  -r requirements/ci_requirements.txt
- pip install Pillow --use-mirrors
- touch onepercentclub/settings/secrets.py
before_script:
- pip show bluebottle
- grunt compass:dist --bb_path="`pip show bluebottle | grep Location | cut -b11-`/bluebottle/common/static/sass"
script:
- python ./manage.py test --settings=onepercentclub.settings.travis --failfast -v
  1
notifications:
  hipchat:
    rooms:
      secure: lfQxEnp7TBqzVc61Wm8NhQiqkKg6YBSx9Ro1q3VTeUWsKzFS2p7OV1eKu8bXjCA9FaCaaxc/TxFaZcvUr2hzXJiW/VoZH4J/+yYp2yblhj5uzQuQl3oWRgY8eFK33rjelqnkolFSmrMkVWY6cw/M8DNrxoSqzQLP2Dn5jYxS6Jg=
